name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送版本标签时触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: python build.py
      
    - name: Rename artifacts
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          mv dist/SealText.exe dist/SealText-windows.exe
        elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          mv dist/SealText dist/SealText-linux
        else
          mv dist/SealText dist/SealText-macos
        fi
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SealText-${{ matrix.os }}
        path: dist/SealText-*
        
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          SealText-windows-latest/SealText-windows.exe
          SealText-ubuntu-latest/SealText-linux
          SealText-macos-latest/SealText-macos
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 